parameters:
#    blogger_meta_data.example.class: Blogger\MetaDataBundle\Example

services:
#    blogger_meta_data.example:
#        class: %blogger_meta_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
