<?php

namespace Blogger\FriendBundle\Entity\Repository;

use Blogger\FriendBundle\Entity\FriendRequest;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Exception\ConstraintDefinitionException;

/**
 * FriendRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRequestRepository extends EntityRepository
{
    /**
     * 
     * @param Integer $user_id
     * @param Integer $friend_id
     */
    function sendFriendRequest($user_id,$friend_id) {
        $em=  $this->getEntityManager();
        
        $requestByUser=$em->getRepository("BloggerUserBundle:User")->find($user_id);
        $requestToUser=$em->getRepository("BloggerUserBundle:User")->find($friend_id);
        if(!$requestByUser || !$requestToUser ){
            throw new ConstraintDefinitionException("User Object are not valid.");
        }
        $friendRequest=new FriendRequest();
        $friendRequest->setRequestBy($requestByUser);
        $friendRequest->setRequestTo($requestToUser);
        $friendRequest->setStatus(FriendRequest::FRIEND_REQUEST_SEND);
        $em->persist($friendRequest);
        $em->flush($friendRequest);
        
        return $friendRequest;
    }    
}
