blogger_meta_data:
    resource: "@BloggerMetaDataBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

blogger_friend:
    resource: "@BloggerFriendBundle/Controller"
    prefix:   /
    type: annotation

blogger_task:
    resource: "@BloggerTaskBundle/Resources/config/routing.yml"
    prefix:   /

blogger_user:
    resource: "@BloggerUserBundle/Resources/config/routing.yml"
    prefix:   /
    
blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog_new:
    resource: "@BloggerBlogBundle/Resources/config/routing_new.yml"
    prefix:   /

sonata_user:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /admin

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile