blogger_task:
    resource: "@BloggerTaskBundle/Resources/config/routing.yml"
    prefix:   /

blogger_user:
    resource: "@BloggerUserBundle/Resources/config/routing.yml"
    prefix:   /
    
blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog_new:
    resource: "@BloggerBlogBundle/Resources/config/routing_new.yml"
    prefix:   /


    
