fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

blogger_friend:
    resource: "@BloggerFriendBundle/Controller"
    prefix:   /
    type: annotation

blogger_task:
    resource: "@BloggerTaskBundle/Resources/config/routing.yml"
    prefix:   /

blogger_user:
    resource: "@BloggerUserBundle/Resources/config/routing.yml"
    prefix:   /
    
blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog_new:
    resource: "@BloggerBlogBundle/Resources/config/routing_new.yml"
    prefix:   /


    
