security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Blogger\UserBundle\Entity\User:
            algorithm: plaintext
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       chainprovider:
            chain:
                providers: [ in_memory, main ]
           
       in_memory:
               memory:
                  users:
                      user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                      admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
       main:
           entity: 
               class: Blogger\UserBundle\Entity\User
               
    firewalls:
       secured_area:
            pattern:    ^/
            form_login: 
                login_path:  /login
                check_path:  /login_check
                default_target_path: BloggerBlogBundle_homepage
            logout: 
                path: /logout
                target: /
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/user , roles: ROLE_USER }
        - { path: ^/task , roles: ROLE_USER }
        
