<?php

namespace Blogger\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserSecurityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSecurityRepository extends EntityRepository
{
    
}
