BloggerUserBundle_reset_password:
    pattern: /resetpassword/{using}
    defaults: { _controller: BloggerUserBundle:Security:resetPassword, using: email }
    requirements:
      using: email|question   

BloggerUserBundle_change_password:
    pattern: /user/changepassword
    defaults: { _controller: BloggerUserBundle:User:chanegPassword }

BloggerUserBundle_profile_image:
    pattern: /profile/image
    defaults: { _controller: BloggerUserBundle:Profile:image }



BloggerUserBundle_profile:
    pattern: /profile
    defaults: { _controller: BloggerUserBundle:Profile:index }


BloggerUserBundle_user:
    pattern: /user
    defaults: { _controller: BloggerUserBundle:User:index }
    requirements:
      _method: GET


register:
    pattern: /register
    defaults: { _controller: BloggerUserBundle:User:register }

handle_register:
    pattern: /handle_register
    defaults: { _controller: BloggerUserBundle:User:handleRegister }
    
login:
    pattern: /login
    defaults: { _controller: BloggerUserBundle:User:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
    defaults: { _controller: BloggerUserBundle:User:logout }
    

