parameters:
#    blogger_friend.example.class: Blogger\FriendBundle\Example

services:
#    blogger_friend.example:
#        class: %blogger_friend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
