<?php

namespace Blogger\MetaDataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoMetaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoMetaDataRepository extends EntityRepository
{
}
